# Generated by Django 5.2 on 2025-04-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesOfAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان تقدیرنامه')),
                ('image', models.ImageField(upload_to='images/certifications', verbose_name='تقدیرنامه ها')),
                ('status', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تقدیر نامه',
                'verbose_name_plural': 'تقدیر نامه ها',
            },
        ),
        migrations.CreateModel(
            name='ContactMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/projects', verbose_name='تصویر پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('link', models.URLField(blank=True, null=True, verbose_name='آدرس پروژه')),
                ('status', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'پروژه من',
                'verbose_name_plural': 'پروژه های من',
            },
        ),
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مهارت')),
                ('progress_value', models.IntegerField(verbose_name='درصد')),
                ('progress_width', models.IntegerField(verbose_name='عرض')),
                ('status', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'مهارت من',
                'verbose_name_plural': 'مهارت های من',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ارائه')),
                ('image', models.ImageField(upload_to='images/offer', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'ارائه',
                'verbose_name_plural': 'ارائه ها',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(upload_to='images/avatar', verbose_name='تصویر آواتار')),
                ('job_position', models.CharField(max_length=100, verbose_name='سمت شغلی')),
                ('about_me_text', models.TextField(verbose_name='درباره من')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('github', models.URLField(blank=True, null=True, verbose_name='گیتهاب')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('status', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اطلاعات شخصی من',
                'verbose_name_plural': 'اطلاعات های شخصی من',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=100, verbose_name='آدرس سایت')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/site_logo', verbose_name='لوگو سایت')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس')),
                ('copy_right', models.TextField(max_length=500, verbose_name='متن کپی رایت')),
                ('is_main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
