# Generated by Django 5.2 on 2025-04-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_personalinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن همراه'),
        ),
    ]
