# Generated by Django 5.2 on 2025-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_personalinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(upload_to='images/offer', verbose_name='تصویر'),
        ),
    ]
