# Generated by Django 5.2 on 2025-04-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_offer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سرویس')),
                ('image', models.FileField(upload_to='images/offer', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
