# Generated by Django 5.1.7 on 2025-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_personalinfo_my_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='my_resume',
            field=models.FileField(blank=True, null=True, upload_to='medias/files/my_resume', verbose_name='رزومه من'),
        ),
    ]
